import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Local Chrome DevTools Protocol bridge: CommonJS Node tooling, not
    // application code, and not subject to the TypeScript lint rules.
    "agent/**",
    // Supabase CLI scratch space, regenerated by `supabase start`. Contains
    // bundled edge-runtime sources that are minified and not ours to lint.
    // Already gitignored; eslint does not inherit .gitignore.
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
